Repository osmlab/atlas-checks, pull requests merged in 2018-10, with the labels that each got.

#71 Intersecting Buildings Check: Refactor to use new IntersectionUtils class
  src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
Labels: enhancement

#69 Invalid Mini Roundabout Check
  config/configuration.json
  dependencies.gradle
  docs/checks/invalidMiniRoundaboutCheck.md
  src/main/java/org/openstreetmap/atlas/checks/validation/points/InvalidMiniRoundaboutCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/points/InvalidMiniRoundaboutCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/points/InvalidMiniRoundaboutCheckTestRule.java
Labels: IntegrityCheck

#75 PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#78 Use trusty and sudo false for Travis
  .travis.yml
Labels: bug

#79 Update Sonar badge
  README.md
Labels: documentation

#80 Log Diff Sonar Bug Fix
  src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksLogDiffSubCommand.java
Labels: bug

#82 Fix Event Service bug
  src/main/java/org/openstreetmap/atlas/checks/event/EventService.java
  src/test/java/org/openstreetmap/atlas/checks/event/EventServiceTest.java
Labels: bug
