Repository osmlab/atlas-checks, pull requests merged in 2018-09, with the labels that each got.

#67 document: running checks on spark cluster
  build.gradle
  docs/cluster.md
Labels: documentation

#66 Mixed Case Name Check
  config/configuration.json
  docs/checks/mixedCaseNameCheck.md
  src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheckTestRule.java
Labels: IntegrityCheck

#70 Unregister processor on the event service
  src/main/java/org/openstreetmap/atlas/checks/event/EventService.java
  src/test/java/org/openstreetmap/atlas/checks/event/EventServiceTest.java
Labels: enhancement
