Repository osmlab/atlas-checks, pull requests merged in 2019-06, with the labels that each got.

#169 Flag Statistics Command Parallel Bug Fix
  src/main/java/org/openstreetmap/atlas/checks/commands/FlagStatisticsSubCommand.java
Labels: bug

#171 Checkstyle RequireThis changed and update was missed
  config/checkstyle/checkstyle.xml
  src/main/java/org/openstreetmap/atlas/checks/base/CheckResourceLoader.java
  src/main/java/org/openstreetmap/atlas/checks/distributed/AtlasFilePathResolver.java
  src/main/java/org/openstreetmap/atlas/checks/distributed/GeoJsonPathFilter.java
  src/main/java/org/openstreetmap/atlas/checks/distributed/LogFilePathFilter.java
  src/main/java/org/openstreetmap/atlas/checks/event/FileProcessor.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Project.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Task.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/serializer/TaskDeserializer.java
  src/main/java/org/openstreetmap/atlas/checks/validation/areas/SpikyBuildingCheck.java
  src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
  src/main/java/org/openstreetmap/atlas/checks/validation/points/AddressPointMatchCheck.java
  src/test/java/org/openstreetmap/atlas/checks/base/PierTest.java
  src/test/java/org/openstreetmap/atlas/checks/base/TagTest.java
  src/test/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/checks/commands/AtlasChecksLogDiffSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/checks/commands/FlagStatisticsSubCommandTestRule.java
  src/test/java/org/openstreetmap/atlas/checks/event/CheckFlagGeoJsonProcessorTestRule.java
  src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTest.java
  src/test/java/org/openstreetmap/atlas/checks/maproulette/TestMapRouletteConnection.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheckTestRule.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/SpikyBuildingCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/SpikyBuildingCheckTestRule.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/WaterbodyAndIslandSizeTestRule.java
  src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolyLineCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/points/AddressPointMatchCheckTestRule.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/ConflictingAreaTagCombinationCheckTestRule.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/UnusualLayerTagsCheckTestRule.java
Labels: enhancement

#176 New check GeneralizedCoastlineCheck
  config/configuration.json
  docs/checks/generalizedCoastlineCheck.md
  src/main/java/org/openstreetmap/atlas/checks/validation/linear/lines/GeneralizedCoastlineCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/GeneralizedCoastlineCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/GeneralizedCoastlineCheckTestRule.java
Labels: IntegrityCheck
