Repository osmlab/atlas-checks, pull requests merged in 2019-08, with the labels that each got.

#183 Add PedestrianAreaOverlappingEdgeCheck
  config/configuration.json
  docs/checks/pedestrianAreaOverlappingEdgeCheck.md
  src/main/java/org/openstreetmap/atlas/checks/validation/areas/PedestrianAreaOverlappingEdgeCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/PedestrianAreaOverlappingEdgeCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/areas/PedestrianAreaOverlappingEdgeCheckTestRule.java
Labels: IntegrityCheck

#182 MalformedRoundaboutCheck Use ComplexRoundabout
  src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
Labels: refactor

#184 Checks database upload Command
  build.gradle
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/checks/database/DatabaseConnection.java
  src/main/java/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommand.java
  src/main/java/org/openstreetmap/atlas/checks/flag/serializer/CheckFlagDeserializer.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
  src/main/java/org/openstreetmap/atlas/checks/utility/FileUtility.java
  src/main/resources/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/checks/database/schema.sql
  src/test/java/org/openstreetmap/atlas/checks/database/DatabaseConnectionTest.java
  src/test/java/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/checks/flag/serializer/CheckFlagDeserializerTest.java
  src/test/resources/org/openstreetmap/atlas/checks/flag/checkflags1.log
  src/test/resources/org/openstreetmap/atlas/checks/flag/checkflags2.log
Labels: enhancement
