Repository osmlab/atlas-checks, pull requests merged in 2020-06, with the labels that each got.

#305 fix traversing via reversed edges.
  src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
  src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheck.java
Labels: bug

#303 InvalidMultiPolygonRelationCheck Overlap Test Limits
  config/configuration.json
  src/main/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheckTest.java
Labels: performance

#307 [MapRouletteUploadCommand] Filter empty lines
  src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
Labels: bug

#317 Vlad roundabout bad tagging
  src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTestRule.java
Labels: bug

#312 [MapRouletteUploadCommand] Various changes to maproulette upload command
  src/main/java/org/openstreetmap/atlas/checks/flag/serializer/CheckFlagDeserializer.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/data/ChallengeStatus.java
  src/main/java/org/openstreetmap/atlas/checks/maproulette/serializer/TaskDeserializer.java
Labels: enhancement
