Repository osmlab/atlas-checks, pull requests merged in 2020-08, with the labels that each got.

#337 Fix issue with InvalidTagsCheck configurables
  config/configuration.json
  src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTagsCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTagsCheckTest.java
Labels: bug

#336 Updates to AtGradeSignPostCheck
  src/main/java/org/openstreetmap/atlas/checks/validation/intersections/AtGradeSignPostCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/intersections/AtGradeSignPostCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/intersections/AtGradeSignPostCheckTestRule.java
Labels: enhancement

#335 Add a Script to Split Atlas Checks Log Files By Check Name
  scripts/check-log-splitter/README.md
  scripts/check-log-splitter/__init__.py
  scripts/check-log-splitter/log_splitter.py
Labels: new feature

#342 New check: Missing bridge structure (#341)
  config/configuration.json
  docs/available_checks.md
  docs/checks/bridgeDetailedInfoCheck.md
  src/main/java/org/openstreetmap/atlas/checks/validation/tag/BridgeDetailedInfoCheck.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/BridgeDetailedInfoCheckTest.java
  src/test/java/org/openstreetmap/atlas/checks/validation/tag/BridgeDetailedInfoCheckTestRule.java
Labels: new integrity check
